#!/usr/bin/env bash
set -euo pipefail

src="${1:-images/chromeos.img}"
out="${2:-images/vmware/chromeos}"
[ -f "$src" ] || { echo "source image not found: $src"; exit 1; }
command -v qemu-img >/dev/null || { echo "qemu-img is required"; exit 1; }
mkdir -p "$(dirname "$out")"

echo "Creating $out.vmdk"
qemu-img convert -p -O vmdk -o subformat=monolithicSparse "$src" "$out.vmdk"

cat > "$out.vmx" <<EOF
.encoding = "UTF-8"
config.version = "8"
virtualHW.version = "17"
displayName = "ChromeOS"
guestOS = "other-64"
firmware = "efi"
memsize = "8192"
numvcpus = "6"
cpuid.coresPerSocket = "6"
vhv.enable = "TRUE"
sata0.present = "TRUE"
sata0:0.present = "TRUE"
sata0:0.fileName = "$(basename "$out").vmdk"
sata0:0.deviceType = "disk"
pciBridge0.present = "TRUE"
pciBridge4.present = "TRUE"
pciBridge4.virtualDev = "pcieRootPort"
pciBridge4.functions = "8"
pciBridge5.present = "TRUE"
pciBridge5.virtualDev = "pcieRootPort"
pciBridge5.functions = "8"
pciBridge6.present = "TRUE"
pciBridge6.virtualDev = "pcieRootPort"
pciBridge6.functions = "8"
pciBridge7.present = "TRUE"
pciBridge7.virtualDev = "pcieRootPort"
pciBridge7.functions = "8"
ethernet0.present = "TRUE"
ethernet0.virtualDev = "e1000e"
ethernet0.connectionType = "nat"
ethernet0.addressType = "generated"
usb.present = "TRUE"
usb_xhci.present = "TRUE"
mks.enable3d = "TRUE"
svga.autodetect = "TRUE"
serial0.present = "TRUE"
serial0.fileType = "file"
serial0.fileName = "serial.log"
serial0.tryNoRxLoss = "TRUE"
sound.present = "TRUE"
sound.virtualDev = "hdaudio"
sound.autodetect = "TRUE"
svga.graphicsMemoryKB = "262144"
powerType.powerOff = "soft"
powerType.powerOn = "hard"
powerType.suspend = "soft"
powerType.reset = "soft"
tools.syncTime = "TRUE"
usb.generic.autoconnect = "FALSE"
EOF
echo "Wrote $out.vmx"
